name: mytology_cicd

on:
  push:
    branches:
      - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Testing
        run: |
          cd stocks_products/
          python manage.py test